### ISSUE TITLE
客户端上传文件失败

### ISSUE THREAD

**Issue by waslee** [happyfish100/fastdfs#149]
5.11版本
storaged.log
[2017-08-24 16:19:31] ERROR - file: storage_nio.c, line: 371, client ip: 192.168.10.180, pkg length: -7599217438042216448 < 0
[2017-08-24 16:19:40] ERROR - file: tracker_proto.c, line: 48, server: 192.168.10.177:23000, response status 2 != 0
[2017-08-24 16:19:40] ERROR - file: tracker_proto.c, line: 48, server: 192.168.10.177:23000, response status 2 != 0
[2017-08-24 16:19:40] ERROR - file: tracker_proto.c, line: 48, server: 192.168.10.177:23000, response status 2 != 0
[2017-08-24 16:19:55] WARNING - file: storage_service.c, line: 7155, client ip: 192.168.10.177, logic file: M00/20/7A/wKgKsVmejBmASx3DAADGlEyIAcg270.jpg not exist
[2017-08-24 16:19:55] WARNING - file: storage_service.c, line: 7155, client ip: 192.168.10.177, logic file: M00/20/7A/wKgKsVmejBmASx3DAADGlEyIAcg270.jpg-m not exist
[2017-08-24 16:20:10] ERROR - file: tracker_proto.c, line: 48, server: 192.168.10.177:23000, response status 2 != 0
[2017-08-24 16:20:10] ERROR - file: tracker_proto.c, line: 48, server: 192.168.10.177:23000, response status 2 != 0
[2017-08-24 16:21:10] ERROR - file: tracker_proto.c, line: 48, server: 192.168.10.177:23000, response status 2 != 0
[2017-08-24 16:21:10] ERROR - file: tracker_proto.c, line: 48, server: 192.168.10.177:23000, response status 2 != 0

tomcat日志:
2017-08-24 16:46:58][ERROR]-com.xxx.upload.dfsutil.FileManager.upload(FileManager.java:89):Non IO Exception when uploadind the file:
 1503564418327
java.lang.NullPointerException
	at org.csource.fastdfs.StorageClient.do_upload_file(StorageClient.java:842)
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:208)
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:226)
	at com.xxxxxx.upload.dfsutil.FileManager.upload(FileManager.java:85)
	at com.xxxxxx.upload.controller.UploadController.orderUpload(UploadController.java:262)
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerM
ethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandler
Adapter.java:814)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapt
er.java:737)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)

------------------------------------------------------------
[2017-08-24 16:47:28][INFO]-com.xxxxx.upload.dfsutil.FileManager.upload(FileManager.java:76):File Name: 1503564448811		File Le
ngth: 50753
[2017-08-24 16:47:28][ERROR]-com.xxxxx.upload.dfsutil.FileManager.upload(FileManager.java:89):Non IO Exception when uploadind the file:
 1503564448811
org.csource.common.MyException: body length: 0 <= 16
	at org.csource.fastdfs.StorageClient.do_upload_file(StorageClient.java:799)
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:208)
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:226)
	at com.xxxxxx.upload.dfsutil.FileManager.upload(FileManager.java:85)
	at com.xxxxxx.upload.controller.UploadController.orderUpload(UploadController.java:262)
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerM
ethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandler
Adapter.java:814)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapt
er.java:737)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:871)

**Comment by waslee** [comment]
fastdfs-client-java  版本1.25

**Comment by ityouknow** [comment]
遇到同样的问题。

**Comment by was1130** [comment]
我也遇到同样的问题

**Comment by Marviszhao** [comment]
我也遇到同样的问题，有没有解决的人，我是使用的多线程调用的。

**Comment by ityouknow** [comment]
@Marviszhao  
是使用的问题：http://www.ityouknow.com//fastdfs/2017/12/26/fastdfs-concurrent.html
