### ISSUE TITLE
 file: storage_nio.c, line: 436, send timeout 大并发情况下出现以上问题

### ISSUE THREAD

**Issue by weiyi1125** [happyfish100/fastdfs#273]
大并发情况下出现以下问题：
1  file: storage_nio.c, line: 436, send timeout 
2  ERROR - file: tracker_service.c, line: 2438, cmd=103, client ip: 172.31.234.99, package size 20 is not correct, expect length > 38
3 客户端连接服务端出现了io异常:socket io exception occured while sending cmd
com.github.tobato.fastdfs.exception.FdfsIOException: 客户端连接服务端出现了io异常:socket io exception occured while sending cmd ； ERROR c.g.t.f.d.proto.AbstractFdfsCommand - send conent error
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:141)

4 receive conent error
java.io.IOException: recv cmd: -27 is not correct, expect cmd: 100
	at com.github.tobato.fastdfs.domain.proto.ProtoHead.validateResponseHead(ProtoHead.java:123)
	at com.github.tobato.fastdfs.domain.proto.AbstractFdfsCommand.receive(AbstractFdfsCommand.java:106)
	at com.github.tobato.fastdfs.domain.proto.AbstractFdfsCommand.execute(AbstractFdfsCommand.java:50)

**Comment by crazyer02** [comment]
我是net调用的也出现了 file: storage_nio.c, line: 436, send timeout这个错误，不知道怎么搞

**Comment by yuboliang** [comment]
你好，请问后面你们如何解决这个问题，我这边也发生了这种问题
