### ISSUE TITLE
删除文件是总是要调用两次接口才可以成功

### ISSUE THREAD

**Issue by ighack** [happyfish100/fastdfs#289]
fastdfs: 5.11
java-client: 1.27
```
public ResultVO deletes(@RequestBody List<String> fileUrls){
        ResultVO resultVO = new ResultVO();
//        List<String> files = fileUrls.get("fileUrls");
        if (fileUrls == null || fileUrls.size()==0) {
            logger.warn("文件路径不能为空");
            resultVO.setErr("文件路径不能为空");
            resultVO.setFlag(false);
            return resultVO;
        }
        TrackerClient trackerClient = null;
        TrackerServer trackerServer = null;
        StorageServer storageServer = null;
        StorageClient storageClient = null;
        int result = -1;
        try{
//            String filePath = new ClassPathResource("fdfs_client.conf").getFile().getAbsolutePath();
            ClientGlobal.init(fastdfsConfig);
            trackerClient = new TrackerClient();
            trackerServer = trackerClient.getConnection();
            if(trackerServer !=null) {
                storageServer = trackerClient.getStoreStorage(trackerServer);
                if(storageServer !=null) {
                    storageClient = new StorageClient(trackerServer, storageServer);
                    if(storageClient !=null) {
                        for (int i = 0; i < fileUrls.size(); i++) {
                            String groupName = fileUrls.get(i).substring(0, fileUrls.get(i).indexOf('/'));
                            String remoteFile = fileUrls.get(i).substring(fileUrls.get(i).indexOf('/')+1);
                            logger.debug(groupName);
                            logger.debug(remoteFile);
                            result = storageClient.delete_file(groupName, remoteFile);
                            if (result != 0) {
                                if(resultVO.getPath() != null){
                                resultVO.setPath(resultVO.getPath() + ";" + fileUrls.get(i));
                                }else{
                                    resultVO.setPath(fileUrls.get(i));
                                }
                            }
                        }
                        if (resultVO.getPath() != null) {
                            resultVO.setCount(-1);
                            resultVO.setFlag(false);
                        } else {
                            resultVO.setCount(result);
                            resultVO.setFlag(true);
                        }
                    }else{
                        throw new IOException("连接storageClient出错");
                    }
                }else{
                    throw new IOException("连接storageServer出错");
                }
            }else{
                throw new IOException("连接trackerServer出错");
            }
        }catch (Exception err){
            logger.error(err.getLocalizedMessage());

            resultVO.setFlag(false);
            resultVO.setCount(-1);
            resultVO.setErr(err.getLocalizedMessage());
        }finally {
            close(trackerServer,storageServer);
        }
        return resultVO;
    }

    private void close(TrackerServer trackerServer,StorageServer storageServer){
        try {
            if(storageServer != null) {
                storageServer.close();
            }
            if(trackerServer != null) {
                trackerServer.close();
            }
        }catch (Exception err){
            logger.error("关闭连接失败："+ err.getLocalizedMessage());
        }
    }
```
每次想删除的时候，第一次调用接口是只的22也没的说明原因。第二次调用就成功了。不知道为什么
还发现有ERROR - file: storage_service.c, line: 7255, client ip:192.168.0.3, group_name: group1 not correct, should be: group2
但我删除的就是group1上的文件啊
192.168.0.3就是group1的机器
我删除group2上的文件时又提示应该是group1
```
2019-05-08 10:10:13.137 fastdfs [http-nio-18787-exec-2] INFO c.j.cloudfastdfs.controller.FileUploadController FileUploadController.java:168 -group1
2019-05-08 10:10:13.138 fastdfs [http-nio-18787-exec-2] INFO c.j.cloudfastdfs.controller.FileUploadController FileUploadController.java:169 -M00/00/00/wKgA6lzRJbyAMpRrAAFPhZzrGbc49..jpg
2019-05-08 10:10:13.139 fastdfs [http-nio-18787-exec-2] INFO c.j.cloudfastdfs.controller.FileUploadController FileUploadController.java:171 -22
2019-05-08 10:10:28.007 fastdfs [http-nio-18787-exec-4] INFO c.j.cloudfastdfs.controller.FileUploadController FileUploadController.java:168 -group1
2019-05-08 10:10:28.007 fastdfs [http-nio-18787-exec-4] INFO c.j.cloudfastdfs.controller.FileUploadController FileUploadController.java:169 -M00/00/00/wKgA6lzRJbyAMpRrAAFPhZzrGbc49..jpg
2019-05-08 10:10:28.008 fastdfs [http-nio-18787-exec-4] INFO c.j.cloudfastdfs.controller.FileUploadController FileUploadController.java:171 -0
```

**Comment by ighack** [comment]
如果数组中的length大于1的时候循环删除的时候还会报

```
java.net.SocketException: 断开的管道 (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
	at org.csource.fastdfs.ProtoCommon.closeSocket(ProtoCommon.java:293)
	at org.csource.fastdfs.TrackerServer.close(TrackerServer.java:71)
	at org.csource.fastdfs.StorageClient.delete_file(StorageClient.java:980)
	at com.joint.cloudfastdfs.controller.FileUploadController.deletes(FileUploadController.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2019-05-08 15:47:46.660 [http-nio-18787-exec-1] ERROR c.j.cloudfastdfs.controller.FileUploadController -recv package size -1 != 10
```

**Comment by ighack** [comment]
storageServer = trackerClient.getStoreStorage(trackerServer);  千万不要加这句话。不然会报很多错误，还会出现报22
网上有些教程就有这句话

**Comment by sjqzhang** [comment]
https://github.com/sjqzhang/go-fastdfs
