### ISSUE TITLE
java.io.IOException: recv cmd: 32 is not correct, expect cmd: 100

### ISSUE THREAD

**Issue by BelieverDZG** [happyfish100/fastdfs#332]
我是基于docker搭建一个fdfs集群，创建了三个节点，如下图
![图片](https://user-images.githubusercontent.com/31923331/65899957-6f8d6a00-e3e7-11e9-9f6f-5a3efb6deb21.png)
测试集群的状况正常，在命令行中上传文件正常，也可以通过浏览器来查看文件，但是代码测试文件上传的时候报出如下错误（同样的代码，在测试服务器上（不是基于docker）的fdfs集群时候可以通过测试）：这会是哪里出的错？？？希望有大佬可以指教下
java.io.IOException: recv cmd: 32 is not correct, expect cmd: 100

	at org.csource.fastdfs.ProtoCommon.recvHeader(ProtoCommon.java:173)
	at org.csource.fastdfs.ProtoCommon.recvPackage(ProtoCommon.java:201)
	at org.csource.fastdfs.TrackerClient.getStoreStorage(TrackerClient.java:130)
	at org.csource.fastdfs.StorageClient.newWritableStorageConnection(StorageClient.java:1627)
	at org.csource.fastdfs.StorageClient.do_upload_file(StorageClient.java:639)
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:120)
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:91)
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:73)
	at com.dzg.test.FastDfsTest.testFastDfs(FastDfsTest.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Process finished with exit code -1

**Comment by Liohoh** [comment]
我也遇到这个问题，TrackerClient.getStoreStorage初始化出问题，加锁，重新加载都没有作用，正在纠结中

**Comment by aboutZZ** [comment]
同遇到此问题

**Comment by syl-skty** [comment]
我遇到的问题也是这样的，但是我是出现在文件下载的地方。
文件下载到一半，之后客户端取消下载。
下一次下载文件文件的请求将会出现这个异常。
研究了一下源码，发现是socket连接池的问题，当第一次下载取消后，会将这次下载建立的socket连接归还到连接池中。
下一次下载时，将会从连接池中获取之前下载取消的那个socket连接，使用这个连接开启输入流后，将会读取到上一次传输的文件内容，导致前面的下载数据传输到这一次下载中，这样在验证下载头的时候就会报错。

我这边的解决方案是：将配置文件中的 fastdfs.connection_pool.enabled   改为false,不使用连接池。

推荐的方法是，修改修改fastDFS-client的源码。
```
 public int download_file(String group_name, String remote_filename,
                             long file_offset, long download_bytes,
                             DownloadCallback callback) throws IOException, MyException {
        int result;
        boolean bNewStorageServer = this.newReadableStorageConnection(group_name, remote_filename);
        Connection connection = this.storageServer.getConnection();

        try {
            ProtoCommon.RecvHeaderInfo header;
            this.send_download_package(group_name, remote_filename, file_offset, download_bytes, connection);

            InputStream in = connection.getInputStream();
            header = ProtoCommon.recvHeader(in, ProtoCommon.STORAGE_PROTO_CMD_RESP, -1);
            this.errno = header.errno;
            if (header.errno != 0) {
                return header.errno;
            }

            byte[] buff = new byte[2 * 1024];
            long remainBytes = header.body_len;
            int bytes;

            //System.out.println("expect_body_len=" + header.body_len);

            while (remainBytes > 0) {
                if ((bytes = in.read(buff, 0, remainBytes > buff.length ? buff.length : (int) remainBytes)) < 0) {
                    throw new IOException("recv package size " + (header.body_len - remainBytes) + " != " + header.body_len);
                }

                if ((result = callback.recv(header.body_len, buff, bytes)) != 0) {
                    this.errno = (byte) result;
                    return result;
                }

                remainBytes -= bytes;
                //System.out.println("totalBytes=" + (header.body_len - remainBytes));
            }

            return 0;
        } catch (IOException ex) {
            try {
                connection.close();
            } catch (IOException ex1) {
                ex1.printStackTrace();
            } finally {
                connection = null;
            }
            throw ex;
        } finally {
            releaseConnection(connection, bNewStorageServer);
        }
    }
```

之前的源代码中只是会出现IOException才会直接将连接移除（不是归还到连接池，而是直接关闭socket连接），
这会导致我们代码中出现异常（不是IOexception）时将仍然会把这个连接回收到连接池，但是其连接中的数据还是上一次传输的数据。我们可以将只捕获IOException改为捕获Exception，这样只要出现异常，就会直接将当前连接弃用，而不是返回到连接池中，不会影响到下一次传输。

这个只是下载的时候出现该异常的处理方式，文件上传出现这个问题，感觉跟这个问题应该差不多，可以参考改一下。

希望这个对你有帮助
