### ISSUE TITLE
上传文件报错：java.io.IOException: recv body length: 70 is not correct, expect length: 40

### ISSUE THREAD

**Issue by Yuuu8** [happyfish100/fastdfs#679]
java.io.IOException: recv body length: 70 is not correct, expect length: 40
        at csource.fastdfs.ProtoCommon.recvHeader(ProtoCommon.java:186)
        at csource.fastdfs.ProtoCommon.recvPackage(ProtoCommon.java:201)
        at csource.fastdfs.TrackerClient.getStoreStorage(TrackerClient.java:130)
        at csource.fastdfs.StorageClient.newWritableStorageConnection(StorageClient.java:1628)
        at csource.fastdfs.StorageClient.do_upload_file(StorageClient.java:640)
        at csource.fastdfs.StorageClient.upload_file(StorageClient.java:163)
        at csource.fastdfs.StorageClient.upload_file(StorageClient.java:181)
        at rent.basecore.fastdfs.FileManager.upload(FileManager.java:71)

请问大佬这个是什么问题

**Comment by Yuuu8** [comment]
我之前用的版本是fastdfs5.11这套代码没问题，现在升级到6.11 就会出现这样的报错

**Comment by senmaowang** [comment]
这个是 fastdfs-clint-java 1.31版本的问题，回退回1.30或者更早版本就好了

**Comment by happyfish100** [comment]
server 端使用 V6.11，fastdfs-clint-java需要使用最新的 V1.31

**Comment by condywl** [comment]
> server 端使用 V6.11，fastdfs-clint-java需要使用最新的 V1.31

大佬，python的客户端 fdfs-client-py3==1.0.0 也报这个错误，求教如何解决。

**Comment by happyfish100** [comment]
为了支持IPv6，返回的IP地址长度由16增大到 46，C client API 和 Java client SDK均已更新。
需要把FDFS的python SDK升级一下。

**Comment by condywl** [comment]
> 为了支持IPv6，返回的IP地址长度由16增大到 46，C client API 和 Java client SDK均已更新。 需要把FDFS的python SDK升级一下。

 还请大佬解答一下新sdk的包名。

**Comment by waketzheng** [comment]
@condywl Python可用这个[fastdfs-client-python](https://github.com/waketzheng/fastdfs-client-python)

Usage::
```py
from fastdfs_client import FastdfsClient  # pip install fastdfs-client

tracker_conf_path = "./tracker.conf"  # tracker配置文件的地址
client = FastdfsClient(tracker_conf_path)

ret = client.upload_by_filename('kitty.jpg')  # 本地文件路径
print(ret)
```

**Comment by happyfish100** [comment]
FDFS 通信协议中涉及 IP 地址的地方，长度由之前的 16 改为 46 了。
请在 client SDK 中做相应修改即可。
