### ISSUE TITLE
上传100M的大文件，一直报 read time out

### ISSUE THREAD

**Issue by marksnoopy** [happyfish100/fastdfs#70]
客户端的超时时间和 fdfs 的超时时间均已修改的比较大，如下：

> connect_timeout = 1800
> network_timeout = 1800

错误如下：

`Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:150)
        at java.net.SocketInputStream.read(SocketInputStream.java:121)
        at java.net.SocketInputStream.read(SocketInputStream.java:107)
        at org.csource.fastdfs.ProtoCommon.recvHeader(ProtoCommon.java:206)
        at org.csource.fastdfs.ProtoCommon.recvPackage(ProtoCommon.java:244)
        at org.csource.fastdfs.StorageClient.delete_file(StorageClient.java:1119)
        at org.csource.fastdfs.StorageClient.do_upload_file(StorageClient.java:835)
        at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:164)
        at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:132)
        at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:114)
        at org.csource.fastdfs.StorageClient1.upload_file1(StorageClient1.java:67)
        at utils.FastDFSUtils.uploadFile(FastDFSUtils.java:104)`

**Comment by marksnoopy** [comment]
fdfs 版本是 3.11

**Comment by shinobi-x** [comment]
问题解决了，FastDFS服务端storage配置的超时时间单位是秒，客户端超时时间的单位是毫秒。
